server:
  port: 9000
  showSwaggerDocs: false
logging:
  level: 'debug'
  color: true
  showStackTraces: true
postgres:
  enabled: true
  logQueries: false
  logQueryResults: false
  host: 'localhost'
  port: '5432'
  database: 'api'
  username: 'admin'
  password: 'admin'
  clientPoolSize: 4